name: "Sample Python Container Action Template"
description: "Sample get started with Python Container actions"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
